site:
  title: Apache Isis
  url: https://isis.apache.org/
  start_page: toc:ROOT:about.adoc

content:
  sources:

# antora
    - url: .
      start_path: antora/toc # toc
      branches: HEAD


# api
    - url: .
      start_path: api/adoc/refguide # refguide
      branches: HEAD
    - url: .
      start_path: api/adoc/userguide # userguide
      branches: HEAD
    - url: .
      start_path: api/applib/src/main/adoc # refguide
      branches: HEAD
    - url: .
      start_path: api/schema/src/main/adoc # refguide
      branches: HEAD

# core
    - url: .
      start_path: core/adoc # core
      branches: HEAD
    - url: .
      start_path: core/codegen-bytebuddy/src/main/adoc # core
      branches: HEAD
    - url: .
      start_path: core/commons/src/main/adoc # core
      branches: HEAD
    - url: .
      start_path: core/config/src/main/adoc # refguide
      branches: HEAD
    - url: .
      start_path: core/detached-tests/src/main/adoc # core
      branches: HEAD
    - url: .
      start_path: core/metamodel/src/main/adoc # core
      branches: HEAD
    - url: .
      start_path: persistence/jdo/src/main/adoc # pjdo
      branches: HEAD
    - url: .
      start_path: core/runtime/src/main/adoc # core
      branches: HEAD
    - url: .
      start_path: core/runtimeservices/src/main/adoc # core
      branches: HEAD
    - url: .
      start_path: core/webapp/src/main/adoc # core
      branches: HEAD
    - url: .
      start_path: core/security/src/main/adoc # security
      branches: HEAD
    - url: .
      start_path: core/unittestsupport/src/main/adoc # testing
      branches: HEAD
    - url: .
      start_path: viewers/restfulobjects/adoc # vro
      branches: HEAD
    - url: .
      start_path: viewers/wicket/adoc # vw
      branches: HEAD

# examples
    - url: .
      start_path: examples/demo/src/main/adoc # demoapp
      branches: HEAD
    - url: .
      start_path: examples/smoketests/src/main/adoc # core
      branches: HEAD

# extensions
    - url: .
      start_path: extensions/adoc # extensions
      branches: HEAD

    - url: .
      start_path: extensions/core/flyway/adoc # userguide
      branches: HEAD

    - url: .
      start_path: extensions/security/secman/adoc # security
      branches: HEAD
    - url: .
      start_path: extensions/security/shiro-realm-ldap/adoc # security
      branches: HEAD

    - url: .
      start_path: extensions/vro/cors/adoc # vro
      branches: HEAD
    - url: .
      start_path: extensions/vw/exceldownload/adoc # vw
      branches: HEAD
    - url: .
      start_path: extensions/vw/fullcalendar/adoc # vw
      branches: HEAD
    - url: .
      start_path: extensions/vw/pdfjs/adoc # vw
      branches: HEAD

# incubator
    - url: .
      start_path: incubator/adoc # incubator
      branches: HEAD
    - url: .
      start_path: incubator/core/model/src/main/adoc # incubator
      branches: HEAD
    - url: .
      start_path: incubator/mappings/microprofile/src/main/adoc # incubator
      branches: HEAD

# legacy
    - url: .
      start_path: legacy/adoc # legacy
      branches: HEAD
    - url: .
      start_path: legacy/extensions/core/applib/src/main/adoc # legacy
      branches: HEAD
    - url: .
      start_path: legacy/extensions/core/commons/src/main/adoc # legacy
      branches: HEAD
    - url: .
      start_path: legacy/extensions/core/runtime/src/main/adoc # legacy
      branches: HEAD
    - url: .
      start_path: legacy/mappings/restclient/src/main/adoc # legacy
      branches: HEAD
    - url: .
      start_path: legacy/subdomains/servletapi/src/main/adoc # legacy
      branches: HEAD

# mappings
    - url: .
      start_path: mappings/adoc # mappings
      branches: HEAD
    - url: .
      start_path: mappings/jaxrsclient/adoc # mappings
      branches: HEAD
    - url: .
      start_path: mappings/minio/adoc # mappings
      branches: HEAD
    - url: .
      start_path: mappings/restclient/adoc # mappings
      branches: HEAD
    - url: .
      start_path: mappings/slack/adoc # mappings
      branches: HEAD

# mavendeps
    - url: .
      start_path: mavendeps/adoc # starters
      branches: HEAD

# security
    - url: .
      start_path: security/adoc # security
      branches: HEAD
    - url: .
      start_path: security/bypass/src/main/adoc # security
      branches: HEAD
    - url: .
      start_path: security/shiro/src/main/adoc # security
      branches: HEAD
    - url: .
      start_path: security/keycloak/src/main/adoc # security
      branches: HEAD

# starters
    - url: .
      start_path: starters/adoc # toc
      branches: HEAD

# subdomains
    - url: .
      start_path: subdomains/adoc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/base/adoc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/docx/adoc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/excel/adoc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/freemarker/adoc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/ognl/adoc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/pdfbox/adoc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/spring/adoc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/xdocreport/adoc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/zip/adoc # subdomains
      branches: HEAD

# testing
    - url: .
      start_path: testing/adoc # testing
      branches: HEAD
    - url: .
      start_path: testing/fakedata/adoc # testing
      branches: HEAD
    - url: .
      start_path: testing/fixtures/adoc # testing
      branches: HEAD
    - url: .
      start_path: testing/h2console/adoc # testing
      branches: HEAD
    - url: .
      start_path: testing/hsqldbmgr/adoc # testing
      branches: HEAD
    - url: .
      start_path: testing/integtestsupport/adoc # testing
      branches: HEAD
    - url: .
      start_path: testing/specsupport/adoc # testing
      branches: HEAD
    - url: .
      start_path: testing/unittestsupport/adoc # testing
      branches: HEAD

# valuetypes
    - url: .
      start_path: valuetypes/adoc # valuetypes
      branches: HEAD
    - url: .
      start_path: valuetypes/asciidoc/adoc # valuetypes
      branches: HEAD
    - url: .
      start_path: valuetypes/markdown/adoc # valuetypes
      branches: HEAD
    - url: .
      start_path: valuetypes/sse/adoc # valuetypes
      branches: HEAD

ui:
  bundle:
#    url: ../isis-antora/build/ui-bundle.zip
    url: https://github.com/apache/isis-antora/blob/master/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: antora/supplemental-ui

asciidoc:
  extensions:
    - asciidoctor-plantuml
    - ./antora/lib/lorem
    - ./antora/lib/jira-issue
  attributes:
    experimental: ""
    idprefix: ""
    idseparator: "-"
    plantuml-server-url: "http://www.plantuml.com/plantuml"
    isiscurr: "2.0.0-M2"
    isisnext: "2.0.0-M3"
    isisnextafter: "2.0.0-M4"
    :isisdevafter: "2.0.0-M4-SNAPSHOT"

output:
  dir: antora/target/site
